@baseUrl = http://localhost:5185

### Login
# @name login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "Username": "admin",
  "Password": "Password123$"
}

### Crear orden
POST {{baseUrl}}/api/orders
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "customerName": "Esta es la tercera prueba",
  "totalAmount": 51.10
}

### Obtener orden por ID
GET {{baseUrl}}/api/orders/1e02c8e7-a156-4750-8948-8ca002ba4c3e
Authorization: Bearer {{login.response.body.token}}

### Obtener todas las órdenes
GET {{baseUrl}}/api/orders?page=1&pageSize=10
Authorization: Bearer {{login.response.body.token}}


